spring.application.name=backend

google.client.id=""
google.client.secret=""
google.redirect.uri=""


# ---- H2 in-memory database ----
spring.datasource.url=jdbc:h2:mem:omvrti-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---- H2 console ----
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console